services:
  - type: web
    name: send-email
    env: java
    plan: free
    buildCommand: mvn clean package
    startCommand: java $JAVA_OPTS -jar target/dependency/webapp-runner.jar --port $PORT target/*.war
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m
