services:
  - type: web
    name: send-email
    env: java
    region: singapore
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Xmx512m -Xms256m -jar target/dependency/webapp-runner.jar --port $PORT target/*.war
    healthCheckPath: /
