services:
  - type: web
    name: send-email-web
    env: java
    region: singapore
    plan: free
    buildCommand: mvn clean install -DskipTests
    startCommand: java -Xmx512m -Xms256m -jar target/dependency/webapp-runner.jar --port $PORT target/send-email.war
